/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import communication.Operation;
import communication.Request;
import communication.Response;
import communication.StatusOdgovora;
import domain.Grupa;
import domain.Profil;
import exception.ClassException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author teodo
 */
public class FrmKreiranjeProfila extends javax.swing.JDialog {

    /**
     * Creates new form FrmKreiranjeProfila
     */
    public FrmKreiranjeProfila(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        napuniComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtJmbg = new javax.swing.JTextField();
        txtGodiste = new javax.swing.JTextField();
        cmbGrupa = new javax.swing.JComboBox<>();
        btnSacuvaj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Novi profil")));

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("JMBG:");

        jLabel5.setText("Grupa:");

        txtGodiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGodisteActionPerformed(evt);
            }
        });

        cmbGrupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGrupaActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel4.setText("Godina rodjenja:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtJmbg, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(txtPrezime)
                                .addComponent(txtGodiste))
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnSacuvaj)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGodiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnSacuvaj)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbGrupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGrupaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGrupaActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        try {
           
            String ime = txtIme.getText();
            String prezime = txtPrezime.getText();
            String jmbg = txtJmbg.getText();
            String godiste=txtGodiste.getText();
            
            proveri(ime,prezime,jmbg,godiste);
            int god = Integer.valueOf(txtGodiste.getText());
            Grupa g = (Grupa) cmbGrupa.getSelectedItem();
            Profil p = new Profil();
            p.setGodiste(god);
            p.setGrupa(g);
            p.setIme(ime);
            p.setPrezime(prezime);
            p.setJMBG(jmbg);
            Response rs = new Response();

            rs = (Response) communication.Communication.getInstance().sacuvajProfil(p);

            if (rs.getException()== null) {
                JOptionPane.showMessageDialog(this, "Usepsno ste kreirali profil");
                int odg = JOptionPane.showConfirmDialog(this, "Da li zelite da dodate novog clana?");
                if (odg == JOptionPane.YES_OPTION) {
                    txtGodiste.setText("");
                    txtIme.setText("");
                    txtJmbg.setText("");
                    txtPrezime.setText("");

                }else{
                    this.dispose();
                }}else{
            JOptionPane.showMessageDialog(this, "Neuspesno ste kreirali profil");
            }

            
        }catch(ClassException e){
        JOptionPane.showMessageDialog(this, "Soket je zatvoren "+e.getMessage());
        this.dispose();
        // TODO add your handling code here:
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem nije kreirao profil\n"+ex.getMessage());
            //System.exit(0);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void txtGodisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGodisteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGodisteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Grupa> cmbGrupa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtGodiste;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJmbg;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void napuniComboBox() {
        try {
            Request request = new Request(Operation.VRATI_GRUPE, FRAMEBITS);

            List<Grupa> grupe = communication.Communication.getInstance().vratiGrupe();
            for (Grupa g : grupe) {
                cmbGrupa.addItem(g);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            // Logger.getLogger(FrmKreiranjeProfila.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void proveri(String ime, String prezime, String jmbg, String godiste) throws Exception {
        String greska="";
        if(ime.isEmpty()){
        greska+="Ime profila mora biti popunjen";
        }
        if(prezime.isEmpty()){
        greska+="Prezime profila mora biti popunjeno";
        }
        if(jmbg.isEmpty() || jmbg.length()!=13 || !jmbg.matches("[0-9]+")){
        greska+="Jmbg mora biti ispravan";
        }
        if(godiste.isEmpty()){
        greska+="Godiste mora biti popunjeno";
        }
        try{
            int godisteInt=Integer.parseInt(godiste);
        }catch(NumberFormatException ex){
        greska+="Godiste mora biti broj";
        }
        if(!greska.isEmpty()){
        throw new Exception(greska);
        }
    }
}
