/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import domain.Profil;
import exception.ClassException;
import form.model.tmNadjeniProfili;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author teodo
 */
public class FrmPretrazivanjeProfila extends javax.swing.JDialog {
static Profil p;
    /**
     * Creates new form FrmPretrazivanjeProfila
     */
    public FrmPretrazivanjeProfila(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
         List<Profil> profili = communication.Communication.getInstance().vratiProfile();
            System.out.println(profili + "forma");

            tmNadjeniProfili tm = new tmNadjeniProfili(profili);

            tblKorisnici.setModel(tm);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKorisnici = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        btnPretrazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Korisnici:");

        tblKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKorisnici);

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(10, 10, 10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnPretrazi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnDetalji)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPretrazi)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetalji)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed

        String ime = txtIme.getText();
        //String prezime=txtPrezime.getText();

        Profil p1 = new Profil();
        p1.setIme(ime);
        
        // p.setPrezime(prezime);
        p1.setId(-1L);
        //this.p=p1;

        try {
            List<Profil> profili = communication.Communication.getInstance().vratiProfilePoUslovu(p1);
            System.out.println(profili + "forma");

            if(profili.isEmpty()){
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje profile po zadatoj vrednosti");
            return;
            }
            tmNadjeniProfili tm = new tmNadjeniProfili(profili);
            

            tblKorisnici.setModel(tm);
              
        }catch(ClassException e){
        JOptionPane.showMessageDialog(this, "Soket je zatvoren "+e.getMessage());
        this.dispose();
        // TODO add your handling code here:
        } // TODO add your handling code here:
         catch (Exception ex) {
           // Logger.getLogger(FrmPretrazivanjeProfila.class.getName()).log(Level.SEVERE, null, ex);
        
           JOptionPane.showMessageDialog(this, "Neuspesno");
           System.exit(0);
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed

        
        int selektovani = tblKorisnici.getSelectedRow();
        if (selektovani == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita profil");
            return;
        }
        tmNadjeniProfili model = (tmNadjeniProfili) tblKorisnici.getModel();
        
        Profil pe = model.getProfili().get(selektovani);
        FrmProfil fp = new FrmProfil(null, true, pe,this);
        JOptionPane.showMessageDialog(this, "Sistem je ucitao profil");
        fp.setVisible(true);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetaljiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKorisnici;
    private javax.swing.JTextField txtIme;
    // End of variables declaration//GEN-END:variables

    void osveziTabelu(Profil p1)  {
        
        tmNadjeniProfili tm=(tmNadjeniProfili) tblKorisnici.getModel();
        tm.osvezi(p1);
//        try{
//        List<Profil> profili = communication.Communication.getInstance().vratiProfile();
//            System.out.println(profili + "forma");
//
//           tmNadjeniProfili t=new tmNadjeniProfili(profili);
//           tblKorisnici.setModel(t);
//        }catch(Exception e){
//        
//        }
//            tmNadjeniProfili tm = (tmNadjeniProfili) tblKorisnici.getModel();
//            tm.getProfili().remove(p1);
//            tm.osvezi();

            
    }
}
