/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import communication.Operation;
import communication.Request;
import communication.Response;
import domain.Grupa;
import domain.Profil;
import domain.Zakazivanje;
import exception.ClassException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author teodo
 */
public class FrmProfil extends javax.swing.JDialog {

    Profil p;
    FrmPretrazivanjeProfila fp;

    /**
     * Creates new form FrmProfil
     */
    public FrmProfil(java.awt.Frame parent, boolean modal, Profil p, FrmPretrazivanjeProfila profil) {
        super(parent, modal);
        initComponents();
        this.p = p;
        this.fp = profil;

        napuniComboBox();
        txtGodina.setEnabled(false);
        txtId.setEnabled(false);
        txtIme.setEnabled(false);
        txtPrezime.setEnabled(false);
        cmbGrupa.setEnabled(false);
        txtJMBG.setEnabled(false);

        txtGodina.setText(p.getGodiste() + "");
        txtId.setText(p.getProfilId() + "");
        txtIme.setText(p.getIme());
        txtPrezime.setText(p.getPrezime());
        txtJMBG.setText(p.getJMBG() + "");
        cmbGrupa.setSelectedItem(p.getGrupa());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtGodina = new javax.swing.JTextField();
        cmbGrupa = new javax.swing.JComboBox<>();
        btnRezervacije = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtJMBG = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Profil"));

        jLabel1.setText("ID:");

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("Godina rodjenja:");

        jLabel5.setText("Grupa:");

        cmbGrupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGrupaActionPerformed(evt);
            }
        });

        btnRezervacije.setText("Rezervacije");
        btnRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRezervacijeActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel6.setText("JMBG:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRezervacije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGodina)
                                    .addComponent(cmbGrupa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtIme)
                                    .addComponent(txtPrezime)
                                    .addComponent(txtJMBG))))))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnRezervacije)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        txtGodina.setEnabled(true);
        txtIme.setEnabled(true);
        txtPrezime.setEnabled(true);
        cmbGrupa.setEnabled(true);
        txtJMBG.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            String ime = txtIme.getText();
            String prezime = txtPrezime.getText();
            long id = Long.parseLong(txtId.getText());
            Grupa g = (Grupa) cmbGrupa.getSelectedItem();
            String godina = txtGodina.getText();

            String jmbg = txtJMBG.getText();
            proveri(ime, prezime, jmbg, godina);

            int god = Integer.parseInt(godina);
            if (ime.equals(p.getIme()) && prezime.equals(p.getPrezime()) && id == p.getProfilId() && g.equals(p.getGrupa()) && god==p.getGodiste()) {
                 JOptionPane.showMessageDialog(this, "Niste promenili nista");
                 return;
            }
            Profil p1 = new Profil(id, ime, prezime, jmbg, god, g);

        this.p = p1;

            communication.Communication.getInstance().izmeniProfil(p1);
            JOptionPane.showMessageDialog(this, "Uspesno ste izmenili podatke o članu.");

            txtGodina.setEnabled(true);
            txtIme.setEnabled(true);
            txtPrezime.setEnabled(true);
            cmbGrupa.setEnabled(true);
            txtJMBG.setEnabled(true);
            if (fp != null) {
                fp.osveziTabelu(p);
            }

        } catch (ClassException e) {
            JOptionPane.showMessageDialog(this, "Soket je zatvoren " + e.getMessage());
            this.dispose();
        } catch (Exception ex) {
            //Logger.getLogger(FrmProfil.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Sistem ne moze da izmeni profil");
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void proveri(String ime, String prezime, String jmbg, String godiste) throws Exception {
        String greska = "";
        if (ime.isEmpty()) {
            greska += "Ime profila mora biti popunjen";
        }
        if (prezime.isEmpty()) {
            greska += "Prezime profila mora biti popunjeno";
        }
        if (jmbg.isEmpty() || jmbg.length() != 13 || !jmbg.matches("[0-9]+")) {
            greska += "Jmbg mora biti ispravan";
        }
        if (godiste.isEmpty()) {
            greska += "Godiste mora biti popunjeno";
        }
        try {
            int godisteInt = Integer.parseInt(godiste);
        } catch (NumberFormatException ex) {
            greska += "Godiste mora biti broj";
        }
        if (!greska.isEmpty()) {
            throw new Exception(greska);
        }
    }
    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        try {
            int odg = JOptionPane.showConfirmDialog(this, "Da li sigurno zelite da obrisete clana?", null, JOptionPane.YES_NO_OPTION);
            if (odg == JOptionPane.YES_OPTION) {
                Zakazivanje z = new Zakazivanje();
                z.setProfil(p);

                int i = communication.Communication.getInstance().obrisiClana(p);
                JOptionPane.showMessageDialog(this, "Clan " + p.getIme() + " " + p.getPrezime() + " je uspesno obrisan.");
                fp.osveziTabelu(p);
                this.dispose();

            }
             }catch(ClassException e){
        JOptionPane.showMessageDialog(this, "Soket je zatvoren "+e.getMessage());
        this.dispose();

        } catch (Exception ex) {
            // Logger.getLogger(FrmProfil.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise profil");

        }

        // TODO add your handling code here:

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void cmbGrupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGrupaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGrupaActionPerformed

    private void btnRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRezervacijeActionPerformed

        FrmRezervisanja fr;
        try {
            fr = new FrmRezervisanja(null, true, p);
            fr.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(FrmProfil.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRezervacijeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnRezervacije;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Grupa> cmbGrupa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtGodina;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void napuniComboBox() {
        try {
            Request request = new Request(Operation.VRATI_GRUPE, FRAMEBITS);

            List<Grupa> grupe = communication.Communication.getInstance().vratiGrupe();
            for (Grupa g : grupe) {
                cmbGrupa.addItem(g);

            }
            } catch (ClassException e) {
            JOptionPane.showMessageDialog(this, "Soket je zatvoren " + e.getMessage());
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(FrmKreiranjeProfila.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }
}
