/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import domain.Grupa;
import domain.Termin;
import exception.ClassException;
import form.model.tmNadjeniProfili;
import form.model.tmNadjeniTermini;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author teodo
 */
public class FrmPretrazivanjeTermina extends javax.swing.JDialog {

    /**
     * Creates new form FrmPretrazivanjeTermina
     */
    public FrmPretrazivanjeTermina(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            List<Termin> lista = communication.Communication.getInstance().vratiTermine();
            tmNadjeniTermini t = new tmNadjeniTermini(lista);

            tblTermini.setModel(t);
         }catch(ClassException e){
        JOptionPane.showMessageDialog(this, "Soket je zatvoren "+e.getMessage());
        this.dispose();
         }
        catch (Exception ex) {
            Logger.getLogger(FrmPretrazivanjeTermina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGrupa = new javax.swing.JTextField();
        cmbPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTermini = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Grupa:");

        cmbPretrazi.setText("Pretrazi");
        cmbPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPretraziActionPerformed(evt);
            }
        });

        tblTermini.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTermini);

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(cmbPretrazi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnDetalji)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cmbPretrazi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetalji)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPretraziActionPerformed

        String g = txtGrupa.getText();
        Grupa grupa = new Grupa();
        grupa.setNazivGrupe(g);
        try {
            grupa = communication.Communication.getInstance().vratiGrupuPoUslovu(grupa);
            if (grupa == null) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da nadje termine po zadatoj vrednosti");

            }

        }    
        catch(ClassException e){
        JOptionPane.showMessageDialog(this, "Soket je zatvoren "+e.getMessage());
        this.dispose();
        // TODO add your handling code here:
}catch (Exception ex) {
            Logger.getLogger(FrmPretrazivanjeTermina.class.getName()).log(Level.SEVERE, null, ex);
        }
        Termin termin = new Termin();
        termin.setGrupa(grupa);
        try {
            List<Termin> termini = communication.Communication.getInstance().vratiTerminePoUslovu(termin);
            System.out.println(termini + "forma");
            if (termini.isEmpty() || termini == null) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da nadje termine po zadatoj vrednosti");
            } else {
                JOptionPane.showMessageDialog(this, "Sistem je nasao termine po zadatoj vrednosti");

                tmNadjeniTermini tm = new tmNadjeniTermini(termini);

                tblTermini.setModel(tm);
            }
            // TODO add your handling code here:
        }    
        catch(ClassException e){
        JOptionPane.showMessageDialog(this, "Soket je zatvoren "+e.getMessage());
        this.dispose();
        // TODO add your handling code here:
        }catch (Exception ex) {
            //Logger.getLogger(FrmPretrazivanjeProfila.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPretraziActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed

        // JOptionPane.showMessageDialog(this, "Sistem je nasao termin");
        int selektovani = tblTermini.getSelectedRow();
        if (selektovani == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita termin!");
            return;
        }
        tmNadjeniTermini model = (tmNadjeniTermini) tblTermini.getModel();
        Termin t = model.getTermini().get(selektovani);
        FrmTermin ft;
        try {
            ft = new FrmTermin(null, true, t,this);
            ft.setVisible(true);
             }catch(ClassException e){
        JOptionPane.showMessageDialog(this, "Soket je zatvoren "+e.getMessage());
        this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(FrmPretrazivanjeTermina.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetaljiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton cmbPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTermini;
    private javax.swing.JTextField txtGrupa;
    // End of variables declaration//GEN-END:variables

    void osvezi(Termin te) {
        tmNadjeniTermini t=(tmNadjeniTermini) tblTermini.getModel();
        t.osvezi(te);
    }
}
