/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import communication.Operation;
import communication.Request;
import domain.Grupa;
import domain.Jezik;
import domain.Termin;
import exception.ClassException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author teodo
 */
public class FrmTermin extends javax.swing.JDialog {

    Termin t;

    FrmPretrazivanjeTermina fpp;
    /**
     * Creates new form FrmKreiranjeTermina
     */
    public FrmTermin(java.awt.Frame parent, boolean modal, Termin t,FrmPretrazivanjeTermina fpp) throws Exception {
        super(parent, modal);
        initComponents();
        JOptionPane.showMessageDialog(this, "Sistem je nasao termin");
        this.t = t;
        this.fpp=fpp;
        napuniComboBox();
        txttId.setText(t.getTerminId()+"");
       popuniJezik(t.getGrupa());
        txtDan.setText(t.getDan());
        txtVreme.setText(t.getVreme());
        cmbGrupa.setSelectedItem(t.getGrupa());
       txtJezik.setText(t.getGrupa().getJezik().getNaziv());
        btnSacuvaj.setEnabled(false);
        txtDan.setEnabled(false);
        txtVreme.setEnabled(false);
        cmbGrupa.setEnabled(false);
        txtJez.setEnabled(false);
        txttId.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJezik = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbGrupa = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtVreme = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnIzmeni = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        txtJez = new javax.swing.JTextField();
        txtDan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Novi termin"));

        jLabel1.setText("Dan:");

        jLabel2.setText("Grupa:");

        cmbGrupa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbGrupaItemStateChanged(evt);
            }
        });
        cmbGrupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGrupaActionPerformed(evt);
            }
        });

        jLabel3.setText("Vreme:");

        jLabel5.setText("ID:");

        jLabel4.setText("Jezik:");

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(txtVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttId, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(42, 42, 42))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbGrupa, 0, 138, Short.MAX_VALUE)
                            .addComponent(txtJez))))
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnIzmeni)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtJez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(btnSacuvaj))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        btnSacuvaj.setEnabled(true);
        txtDan.setEnabled(true);
        txtVreme.setEnabled(true);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void cmbGrupaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbGrupaItemStateChanged

        try {
           // popuniJezik((Grupa) cmbGrupa.getSelectedItem());
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(FrmTermin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbGrupaItemStateChanged

    private void cmbGrupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGrupaActionPerformed

//        try {
//            popuniJezik();
//            // TODO add your handling code here:
//        } catch (Exception ex) {
//            Logger.getLogger(FrmTermin.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_cmbGrupaActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
try {
    
        String dan=(String) txtDan.getText();
        if(dan.equals("nedelja") || dan.equals("Nedelja")){
        JOptionPane.showMessageDialog(this, "Nedeljom ne radi skola");
        return;
        }
        if(!dan.equalsIgnoreCase("ponedeljak") && !dan.equalsIgnoreCase("utorak") && !dan.equalsIgnoreCase("sreda") && !dan.equalsIgnoreCase("cetvrtak") && !dan.equalsIgnoreCase("petak") && !dan.equalsIgnoreCase("subota") ){
        JOptionPane.showMessageDialog(this, "Neispravno unet dan");
        return;
        }
        String vreme=txtVreme.getText();
        Grupa g=(Grupa) cmbGrupa.getSelectedItem();
        int id=Integer.valueOf(txttId.getText());
        
        Jezik j=g.getJezik();
        Termin te=new Termin(id, dan, vreme, g);
        List<Termin> termini=communication.Communication.getInstance().vratiTermine();
        for(Termin ter:termini){
        if(ter.getDan().equals(te.getDan()) && ter.getVreme().equals(te.getVreme())){
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti termin!");
            return;
        }
        }
            communication.Communication.getInstance().izmeniTermin(te);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio termin");
            fpp.osvezi(te);
            
           } catch (ClassException e) {
            JOptionPane.showMessageDialog(this, "Soket je zatvoren " + e.getMessage());
            this.dispose(); // TODO add your handling code here:
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da sacuva termin"+ex.getMessage());
            System.exit(0);
                    
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Grupa> cmbGrupa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDan;
    private javax.swing.JTextField txtJez;
    private javax.swing.JTextField txtJezik;
    private javax.swing.JTextField txtVreme;
    private javax.swing.JTextField txttId;
    // End of variables declaration//GEN-END:variables

    private void napuniComboBox() {
        try {
            Request request = new Request(Operation.VRATI_GRUPE, FRAMEBITS);

            List<Grupa> grupe = communication.Communication.getInstance().vratiGrupe();
            for (Grupa g : grupe) {
                cmbGrupa.addItem(g);
            }
            } catch (ClassException e) {
            JOptionPane.showMessageDialog(this, "Soket je zatvoren " + e.getMessage());
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(FrmKreiranjeProfila.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniJezik(Grupa g) throws Exception {
        try{
        Jezik j=communication.Communication.getInstance().vratiJezikPoUslovu(g.getJezik());
        System.out.println("usao u popuni jezik");
        System.out.println(j);
        t.getGrupa().setJezik(j);
        txtJez.setText(j.getNaziv());
        } catch (ClassException e) {
            JOptionPane.showMessageDialog(this, "Soket je zatvoren " + e.getMessage());
            this.dispose();
        }
    }
}
